# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Blog Section
  description: Hero Section with title, subtitle, description, posts and button
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  background_color: "#ffffff"
  title:  SMARTHOME HCM
  sub_title: Sản Phẩm Hot
  url: /blog
  open_new_tab: false
  posts:
    - id: 1
      image: /images/photo4.png
      title: Robot Hút Bụi
      category: Robot NEW

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

_inputs:
  status:
    type: toggle
    label: Active Section
  background_color:
    type: color
    label: Background Color
    
  title:
    type: text
    label: Title Section

  sub_title:
    type: text
    label: Subtitle Section

  posts[*].id:
    type: number
    label: Post ID

  posts[*].image:
    type: image
    label: Post Image

  posts[*].title:
    type: text
    label: Post Title

  posts[*].category:
    type: text
    label: Post Category
