# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Section Branch
  description: Section Branch
  icon: 'i-mdi-home'

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  list_branch:
    - icon: /images/branch1.png
      title: kinh doanh
   
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  status:
    type: toggle
    label: Active Section
  list_branch[*].icon:
    type: image
    label: Icon Item
  list_branch[*].title:
    type: text
    label: Title Item