# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Section Hero
  description: Section Hero
  icon: 'i-mdi-home'

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  background_image: /images/banner-we.png
  title:
  sub_title: 
  button:
    is_show: true
    label: Khám phá thêm
    link: /san-pham
    open_new_tab: false
   
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  status:
    type: toggle
    label: Active Section
  background_image:
    type: image
    label: Background Image Section
  title:
    type: text
    label: Hero title
  sub_title:
    type: textarea
    label: Hero Sub Title
  button.label:
    type: text
    label: label Button
  button.link:
    type: text
    label: Link Button