# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Section Industry 
  description: Section Industry 
  icon: 'i-mdi-home'

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  title: 
  sub_title: 
  content: 

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  status:
    type: toggle
    label: Active Section
  title:
    type: markdown
    label: Title
  sub_title:
    type: text
    label: Sub Title
  content:
    type: textarea
    label: Content