# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Section Media
  description: Section Media
  icon: 'i-mdi-home'

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  background_color: "#FFFFFF"
  title: <h2>Tin tức</h2>
  button:
    is_show: true
    link: /blog
    label: Khám phá thêm
    open_new_tab: false
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  status:
    type: toggle
    label: Active Section
  background_color:
    type: color
    label: Background Color Section
  title:
    type: markdown
    label: Title Section
  button.label:
    type: text
    label: Title Button
  button.link:
    type: text
    label: Link Button