# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Section Product
  description: Section Product
  icon: 'i-mdi-home'

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  background_color: "#FFFFFF"
  title: <h2>SẢN PHẨM TIÊU BIỂU</h2>
  arrow: /images/arrow.png
  arrow_alt: Arrow Alt
  button:
    is_show: true
    label: Xem thêm
    link: /san-pham
    icon: /images/arrow-right.png
    icon_alt: Icon Arrow
    open_new_tab: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  status:
    type: toggle
    label: Active Section
  background_color:
    type: color
    label: Background Color
  title:
    type: markdown
    label: Title
  arrow:
    type: image
    label: Icon Arrow
  arrow_alt:
    type: text
    label: Alt Icon Arrow
  button.label:
    type: text
    label: Label Button
  button.link:
    type: text
    label: Link Button
  button.icon:
    type: image
    label: Icon Button
  button.icon_alt:
    type: text
    label: Alt Icon Button