# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Section Profession
  description: Section Profession
  icon: 'i-mdi-home'

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  title: cơ hội nghề nghiệp
  list_img:
    - title: chuyên viên marketing
      content: Tiếp thị / Marketing , Bán hàng / Kinh doanh , Tiếp thị trực tuyến
      image: /images/profession1.png
      link: /chi-tiet-nganh
   
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  status:
    type: toggle
    label: Active Section
  title:
    type: markdown
    label: Title Section
  list_img[*].image:
    type: image
    label: Image
  list_img[*].title:
    type: text
    label: Title Item
  list_img[*].content:
    type: text
    label: Content Item
  list_img[*].link:
    type: text
    label: Link Item