# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Section Register
  description: Section Register
  icon: 'i-mdi-home'

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  title: đăng kí tư vấn
  sub_title: Nhận thông tin sản phẩm mới, tin khuyến mãi và nhiều hơn nữa.

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  status:
    type: toggle
    label: Active Section
  title:
    type: text
    label: Title Section
  sub_title:
    type: text
    label: Sub Title Section