# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Section Services
  description: Section Services
  icon: 'i-mdi-home'

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  list_item:
    - image: /images/service1.png
      title: Sản Xuất chai lọ
      content: Nhà máy gia công chai nhựa của Tập Đoàn phát triển khoa học Quốc Tế Trường Sinh là một trong những đơn vị chuyên sản xuất can chai nhựa tại Tây Nguyên. Chúng tôi cung cấp đa dạng các sản phẩm, mẫu mã phong phú đáp ứng nhu cầu sử dụng ngày càng cao của quý khách hàng.
      button:
        link: /
        text: Xem thêm

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  status:
    type: toggle
    label: Active Section
  image:
    type: image
    label: Image
  list_item[*].image:
    type: image
    label: Image
  list_item[*].title:
    type: markdown
    label: number
  list_item[*].content:
    type: markdown
    label: content
  list_item[*].button.link:
    type: text
    label: content
  service[*].button.text:
    type: text
    label: content