# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Category Item
  description: Category Item
  icon: 'i-mdi-home'

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  title: <h2>Sản phẩm</h2>
  tenant_id: test1
   
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  status:
    type: toggle
    label: Active Section
  title:
    type: markdown
    label: Title Section
  tenant_id:
    type: text
    label: Tenant_id
