# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Checkout Hero
  description: Checkout Hero
  icon: 'i-mdi-home'

# Defines the structure of this component, as well as the default values
blueprint:
  status: true
  title: Thanh toán
  background_color: '#FFFFFF'
  logo: /images/logo.png
  logo_alt: Logo Alt
  payment_information:
    title_total: >-
      Đơn của bạn là: 
    content: >-
      <p> Đơn hàng của bạn sẽ được thanh toán qua hình thức Internet Banking. Vui lòng kiểm tra hoá đơn và chuyển qua số tài khoản ngân hàng của shop: </p>
      <p><b>Tên: NGUYEN VAN A<br> Stk: 0123214569742133<br> Ngân hàng Vietcombank, chi Nam Kì Khởi Nghĩa, P8, Q.3, TP.HCM<br></b></p>
      <p> để được phục vụ<br> Cảm ơn! </p>
   
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  status:
    type: toggle
    label: Active Section
  title:
    type: text
    label: Title
  background_color:
    type: color
    label: Background Color
  logo:
    type: image
    label: Logo
  logo_alt:
    type: text
    label: Logo Alt
  payment_information.title_total:
    type: text
    label: Title total
  payment_information.content:
    type: markdown
    label: Content
